# Generated by Django 5.2.8 on 2025-11-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "email",
                    models.EmailField(help_text="Email address", max_length=254, unique=True, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=11, null=True, verbose_name="phone"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, help_text="City", max_length=255, null=True, verbose_name="city"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, help_text="Avatar", null=True, upload_to="users/avatars", verbose_name="avatar"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
