# Generated by Django 5.2.8 on 2025-11-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payments",
            new_name="Payment",
        ),
    ]
