# Generated by Django 5.2.8 on 2025-12-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_link_payment_session_id_alter_payment_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True, help_text="Укажи дату оплаты", verbose_name="Дата оплаты"),
        ),
    ]
