# Generated by Django 5.2.8 on 2025-12-22 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0007_alter_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="content_type",
            field=models.ForeignKey(
                help_text="Тип оплачиваемого объекта (курс или урок)",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Тип объекта",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="object_id",
            field=models.PositiveIntegerField(help_text="ID курса или урока", verbose_name="ID объекта"),
        ),
    ]
