# Generated by Django 5.2.8 on 2025-12-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payment_content_type_alter_payment_object_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, help_text="ID цены в Stripe", max_length=255, null=True, verbose_name="Stripe Price ID"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="ID продукта в Stripe",
                max_length=255,
                null=True,
                verbose_name="Stripe Product ID",
            ),
        ),
    ]
