# Generated by Django 5.2.8 on 2026-01-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_payment_stripe_price_id_payment_stripe_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="last login",
            ),
        ),
    ]
