# Generated by Django 5.2.8 on 2025-12-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["-created_at"], "verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
    ]
