# Generated by Django 5.2.8 on 2026-01-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_subscription_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="notification_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="update_at"),
        ),
    ]
